#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTLBIWebApp2012.Codes.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HTLBI2012")]
	public partial class HTLBI2012DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsystbl_UserMenu(systbl_UserMenu instance);
    partial void Updatesystbl_UserMenu(systbl_UserMenu instance);
    partial void Deletesystbl_UserMenu(systbl_UserMenu instance);
    partial void Insertlsttbl_DWTable(lsttbl_DWTable instance);
    partial void Updatelsttbl_DWTable(lsttbl_DWTable instance);
    partial void Deletelsttbl_DWTable(lsttbl_DWTable instance);
    partial void Insertlsttbl_MappingType(lsttbl_MappingType instance);
    partial void Updatelsttbl_MappingType(lsttbl_MappingType instance);
    partial void Deletelsttbl_MappingType(lsttbl_MappingType instance);
    partial void Insertsystbl_UserDashboard(systbl_UserDashboard instance);
    partial void Updatesystbl_UserDashboard(systbl_UserDashboard instance);
    partial void Deletesystbl_UserDashboard(systbl_UserDashboard instance);
    partial void Insertlsttbl_DashboardSource(lsttbl_DashboardSource instance);
    partial void Updatelsttbl_DashboardSource(lsttbl_DashboardSource instance);
    partial void Deletelsttbl_DashboardSource(lsttbl_DashboardSource instance);
    partial void Insertlsttbl_Widget(lsttbl_Widget instance);
    partial void Updatelsttbl_Widget(lsttbl_Widget instance);
    partial void Deletelsttbl_Widget(lsttbl_Widget instance);
    partial void Insertlsttbl_WidgetInteraction(lsttbl_WidgetInteraction instance);
    partial void Updatelsttbl_WidgetInteraction(lsttbl_WidgetInteraction instance);
    partial void Deletelsttbl_WidgetInteraction(lsttbl_WidgetInteraction instance);
    partial void Insertlsttbl_DWColumn(lsttbl_DWColumn instance);
    partial void Updatelsttbl_DWColumn(lsttbl_DWColumn instance);
    partial void Deletelsttbl_DWColumn(lsttbl_DWColumn instance);
    partial void Insertlsttbl_DWTableRelationship(lsttbl_DWTableRelationship instance);
    partial void Updatelsttbl_DWTableRelationship(lsttbl_DWTableRelationship instance);
    partial void Deletelsttbl_DWTableRelationship(lsttbl_DWTableRelationship instance);
    partial void Insertsystbl_Menu(systbl_Menu instance);
    partial void Updatesystbl_Menu(systbl_Menu instance);
    partial void Deletesystbl_Menu(systbl_Menu instance);
    partial void Insertlsttbl_Dashboard(lsttbl_Dashboard instance);
    partial void Updatelsttbl_Dashboard(lsttbl_Dashboard instance);
    partial void Deletelsttbl_Dashboard(lsttbl_Dashboard instance);
    #endregion
		
		public HTLBI2012DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HTLBI2012_ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HTLBI2012DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HTLBI2012DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HTLBI2012DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HTLBI2012DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<systbl_UserMenu> systbl_UserMenus
		{
			get
			{
				return this.GetTable<systbl_UserMenu>();
			}
		}
		
		public System.Data.Linq.Table<lsttbl_DWTable> lsttbl_DWTables
		{
			get
			{
				return this.GetTable<lsttbl_DWTable>();
			}
		}
		
		public System.Data.Linq.Table<lsttbl_MappingType> lsttbl_MappingTypes
		{
			get
			{
				return this.GetTable<lsttbl_MappingType>();
			}
		}
		
		public System.Data.Linq.Table<systbl_UserDashboard> systbl_UserDashboards
		{
			get
			{
				return this.GetTable<systbl_UserDashboard>();
			}
		}
		
		public System.Data.Linq.Table<lsttbl_DashboardSource> lsttbl_DashboardSources
		{
			get
			{
				return this.GetTable<lsttbl_DashboardSource>();
			}
		}
		
		public System.Data.Linq.Table<lsttbl_Widget> lsttbl_Widgets
		{
			get
			{
				return this.GetTable<lsttbl_Widget>();
			}
		}
		
		public System.Data.Linq.Table<lsttbl_WidgetInteraction> lsttbl_WidgetInteractions
		{
			get
			{
				return this.GetTable<lsttbl_WidgetInteraction>();
			}
		}
		
		public System.Data.Linq.Table<lsttbl_DWColumn> lsttbl_DWColumns
		{
			get
			{
				return this.GetTable<lsttbl_DWColumn>();
			}
		}
		
		public System.Data.Linq.Table<lsttbl_DWTableRelationship> lsttbl_DWTableRelationships
		{
			get
			{
				return this.GetTable<lsttbl_DWTableRelationship>();
			}
		}
		
		public System.Data.Linq.Table<systbl_Menu> systbl_Menus
		{
			get
			{
				return this.GetTable<systbl_Menu>();
			}
		}
		
		public System.Data.Linq.Table<lsttbl_Dashboard> lsttbl_Dashboards
		{
			get
			{
				return this.GetTable<lsttbl_Dashboard>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.systbl_UserMenu")]
	public partial class systbl_UserMenu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private System.Guid _UserID;
		
		private string _MenuCode;
		
		private bool _Visible;
		
		private EntityRef<systbl_Menu> _systbl_Menu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnUserIDChanging(System.Guid value);
    partial void OnUserIDChanged();
    partial void OnMenuCodeChanging(string value);
    partial void OnMenuCodeChanged();
    partial void OnVisibleChanging(bool value);
    partial void OnVisibleChanged();
    #endregion
		
		public systbl_UserMenu()
		{
			this._systbl_Menu = default(EntityRef<systbl_Menu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MenuCode
		{
			get
			{
				return this._MenuCode;
			}
			set
			{
				if ((this._MenuCode != value))
				{
					if (this._systbl_Menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMenuCodeChanging(value);
					this.SendPropertyChanging();
					this._MenuCode = value;
					this.SendPropertyChanged("MenuCode");
					this.OnMenuCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visible", DbType="Bit NOT NULL")]
		public bool Visible
		{
			get
			{
				return this._Visible;
			}
			set
			{
				if ((this._Visible != value))
				{
					this.OnVisibleChanging(value);
					this.SendPropertyChanging();
					this._Visible = value;
					this.SendPropertyChanged("Visible");
					this.OnVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="systbl_Menu_systbl_UserMenu", Storage="_systbl_Menu", ThisKey="MenuCode", OtherKey="Code", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public systbl_Menu systbl_Menu
		{
			get
			{
				return this._systbl_Menu.Entity;
			}
			set
			{
				systbl_Menu previousValue = this._systbl_Menu.Entity;
				if (((previousValue != value) 
							|| (this._systbl_Menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._systbl_Menu.Entity = null;
						previousValue.systbl_UserMenus.Remove(this);
					}
					this._systbl_Menu.Entity = value;
					if ((value != null))
					{
						value.systbl_UserMenus.Add(this);
						this._MenuCode = value.Code;
					}
					else
					{
						this._MenuCode = default(string);
					}
					this.SendPropertyChanged("systbl_Menu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lsttbl_DWTable")]
	public partial class lsttbl_DWTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private bool _Visible;
		
		private string _TblCat;
		
		private string _BizCat;
		
		private string _TblName;
		
		private string _TblAliasVI;
		
		private string _TblAliasEN;
		
		private string _RefInfo;
		
		private EntitySet<lsttbl_DWColumn> _lsttbl_DWColumns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnVisibleChanging(bool value);
    partial void OnVisibleChanged();
    partial void OnTblCatChanging(string value);
    partial void OnTblCatChanged();
    partial void OnBizCatChanging(string value);
    partial void OnBizCatChanged();
    partial void OnTblNameChanging(string value);
    partial void OnTblNameChanged();
    partial void OnTblAliasVIChanging(string value);
    partial void OnTblAliasVIChanged();
    partial void OnTblAliasENChanging(string value);
    partial void OnTblAliasENChanged();
    partial void OnRefInfoChanging(string value);
    partial void OnRefInfoChanged();
    #endregion
		
		public lsttbl_DWTable()
		{
			this._lsttbl_DWColumns = new EntitySet<lsttbl_DWColumn>(new Action<lsttbl_DWColumn>(this.attach_lsttbl_DWColumns), new Action<lsttbl_DWColumn>(this.detach_lsttbl_DWColumns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visible", DbType="Bit NOT NULL")]
		public bool Visible
		{
			get
			{
				return this._Visible;
			}
			set
			{
				if ((this._Visible != value))
				{
					this.OnVisibleChanging(value);
					this.SendPropertyChanging();
					this._Visible = value;
					this.SendPropertyChanged("Visible");
					this.OnVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TblCat", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TblCat
		{
			get
			{
				return this._TblCat;
			}
			set
			{
				if ((this._TblCat != value))
				{
					this.OnTblCatChanging(value);
					this.SendPropertyChanging();
					this._TblCat = value;
					this.SendPropertyChanged("TblCat");
					this.OnTblCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BizCat", DbType="NVarChar(255)")]
		public string BizCat
		{
			get
			{
				return this._BizCat;
			}
			set
			{
				if ((this._BizCat != value))
				{
					this.OnBizCatChanging(value);
					this.SendPropertyChanging();
					this._BizCat = value;
					this.SendPropertyChanged("BizCat");
					this.OnBizCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TblName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TblName
		{
			get
			{
				return this._TblName;
			}
			set
			{
				if ((this._TblName != value))
				{
					this.OnTblNameChanging(value);
					this.SendPropertyChanging();
					this._TblName = value;
					this.SendPropertyChanged("TblName");
					this.OnTblNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TblAliasVI", DbType="NVarChar(100)")]
		public string TblAliasVI
		{
			get
			{
				return this._TblAliasVI;
			}
			set
			{
				if ((this._TblAliasVI != value))
				{
					this.OnTblAliasVIChanging(value);
					this.SendPropertyChanging();
					this._TblAliasVI = value;
					this.SendPropertyChanged("TblAliasVI");
					this.OnTblAliasVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TblAliasEN", DbType="NVarChar(100)")]
		public string TblAliasEN
		{
			get
			{
				return this._TblAliasEN;
			}
			set
			{
				if ((this._TblAliasEN != value))
				{
					this.OnTblAliasENChanging(value);
					this.SendPropertyChanging();
					this._TblAliasEN = value;
					this.SendPropertyChanged("TblAliasEN");
					this.OnTblAliasENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefInfo", DbType="NVarChar(1000)")]
		public string RefInfo
		{
			get
			{
				return this._RefInfo;
			}
			set
			{
				if ((this._RefInfo != value))
				{
					this.OnRefInfoChanging(value);
					this.SendPropertyChanging();
					this._RefInfo = value;
					this.SendPropertyChanged("RefInfo");
					this.OnRefInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lsttbl_DWTable_lsttbl_DWColumn", Storage="_lsttbl_DWColumns", ThisKey="TblName", OtherKey="TblName_Virtual")]
		public EntitySet<lsttbl_DWColumn> lsttbl_DWColumns
		{
			get
			{
				return this._lsttbl_DWColumns;
			}
			set
			{
				this._lsttbl_DWColumns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_lsttbl_DWColumns(lsttbl_DWColumn entity)
		{
			this.SendPropertyChanging();
			entity.lsttbl_DWTable = this;
		}
		
		private void detach_lsttbl_DWColumns(lsttbl_DWColumn entity)
		{
			this.SendPropertyChanging();
			entity.lsttbl_DWTable = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lsttbl_MappingType")]
	public partial class lsttbl_MappingType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private string _Type;
		
		private string _TypeMapping;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnTypeMappingChanging(string value);
    partial void OnTypeMappingChanged();
    #endregion
		
		public lsttbl_MappingType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeMapping", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TypeMapping
		{
			get
			{
				return this._TypeMapping;
			}
			set
			{
				if ((this._TypeMapping != value))
				{
					this.OnTypeMappingChanging(value);
					this.SendPropertyChanging();
					this._TypeMapping = value;
					this.SendPropertyChanged("TypeMapping");
					this.OnTypeMappingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.systbl_UserDashboard")]
	public partial class systbl_UserDashboard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private System.Guid _UserID;
		
		private string _DbrdCode;
		
		private bool _Visible;
		
		private string _ShowCells;
		
		private bool _View;
		
		private bool _Add;
		
		private bool _Edit;
		
		private bool _Delete;
		
		private EntityRef<lsttbl_Dashboard> _lsttbl_Dashboard;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnUserIDChanging(System.Guid value);
    partial void OnUserIDChanged();
    partial void OnDbrdCodeChanging(string value);
    partial void OnDbrdCodeChanged();
    partial void OnVisibleChanging(bool value);
    partial void OnVisibleChanged();
    partial void OnShowCellsChanging(string value);
    partial void OnShowCellsChanged();
    partial void OnViewChanging(bool value);
    partial void OnViewChanged();
    partial void OnAddChanging(bool value);
    partial void OnAddChanged();
    partial void OnEditChanging(bool value);
    partial void OnEditChanged();
    partial void OnDeleteChanging(bool value);
    partial void OnDeleteChanged();
    #endregion
		
		public systbl_UserDashboard()
		{
			this._lsttbl_Dashboard = default(EntityRef<lsttbl_Dashboard>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DbrdCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DbrdCode
		{
			get
			{
				return this._DbrdCode;
			}
			set
			{
				if ((this._DbrdCode != value))
				{
					if (this._lsttbl_Dashboard.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDbrdCodeChanging(value);
					this.SendPropertyChanging();
					this._DbrdCode = value;
					this.SendPropertyChanged("DbrdCode");
					this.OnDbrdCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visible", DbType="Bit NOT NULL")]
		public bool Visible
		{
			get
			{
				return this._Visible;
			}
			set
			{
				if ((this._Visible != value))
				{
					this.OnVisibleChanging(value);
					this.SendPropertyChanging();
					this._Visible = value;
					this.SendPropertyChanged("Visible");
					this.OnVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowCells", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ShowCells
		{
			get
			{
				return this._ShowCells;
			}
			set
			{
				if ((this._ShowCells != value))
				{
					this.OnShowCellsChanging(value);
					this.SendPropertyChanging();
					this._ShowCells = value;
					this.SendPropertyChanged("ShowCells");
					this.OnShowCellsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[View]", Storage="_View", DbType="Bit NOT NULL")]
		public bool View
		{
			get
			{
				return this._View;
			}
			set
			{
				if ((this._View != value))
				{
					this.OnViewChanging(value);
					this.SendPropertyChanging();
					this._View = value;
					this.SendPropertyChanged("View");
					this.OnViewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Add]", Storage="_Add", DbType="Bit NOT NULL")]
		public bool Add
		{
			get
			{
				return this._Add;
			}
			set
			{
				if ((this._Add != value))
				{
					this.OnAddChanging(value);
					this.SendPropertyChanging();
					this._Add = value;
					this.SendPropertyChanged("Add");
					this.OnAddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edit", DbType="Bit NOT NULL")]
		public bool Edit
		{
			get
			{
				return this._Edit;
			}
			set
			{
				if ((this._Edit != value))
				{
					this.OnEditChanging(value);
					this.SendPropertyChanging();
					this._Edit = value;
					this.SendPropertyChanged("Edit");
					this.OnEditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Delete]", Storage="_Delete", DbType="Bit NOT NULL")]
		public bool Delete
		{
			get
			{
				return this._Delete;
			}
			set
			{
				if ((this._Delete != value))
				{
					this.OnDeleteChanging(value);
					this.SendPropertyChanging();
					this._Delete = value;
					this.SendPropertyChanged("Delete");
					this.OnDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lsttbl_Dashboard_systbl_UserDashboard", Storage="_lsttbl_Dashboard", ThisKey="DbrdCode", OtherKey="Code", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public lsttbl_Dashboard lsttbl_Dashboard
		{
			get
			{
				return this._lsttbl_Dashboard.Entity;
			}
			set
			{
				lsttbl_Dashboard previousValue = this._lsttbl_Dashboard.Entity;
				if (((previousValue != value) 
							|| (this._lsttbl_Dashboard.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lsttbl_Dashboard.Entity = null;
						previousValue.systbl_UserDashboards.Remove(this);
					}
					this._lsttbl_Dashboard.Entity = value;
					if ((value != null))
					{
						value.systbl_UserDashboards.Add(this);
						this._DbrdCode = value.Code;
					}
					else
					{
						this._DbrdCode = default(string);
					}
					this.SendPropertyChanged("lsttbl_Dashboard");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lsttbl_DashboardSource")]
	public partial class lsttbl_DashboardSource : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private string _Code;
		
		private string _ParentCode;
		
		private string _SettingCat;
		
		private string _WHCode;
		
		private string _NameVI;
		
		private string _NameEN;
		
		private string _NameFormatVI;
		
		private string _NameFormatEN;
		
		private string _JsonStr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnParentCodeChanging(string value);
    partial void OnParentCodeChanged();
    partial void OnSettingCatChanging(string value);
    partial void OnSettingCatChanged();
    partial void OnWHCodeChanging(string value);
    partial void OnWHCodeChanged();
    partial void OnNameVIChanging(string value);
    partial void OnNameVIChanged();
    partial void OnNameENChanging(string value);
    partial void OnNameENChanged();
    partial void OnNameFormatVIChanging(string value);
    partial void OnNameFormatVIChanged();
    partial void OnNameFormatENChanging(string value);
    partial void OnNameFormatENChanged();
    partial void OnJsonStrChanging(string value);
    partial void OnJsonStrChanged();
    #endregion
		
		public lsttbl_DashboardSource()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCode", DbType="NVarChar(50)")]
		public string ParentCode
		{
			get
			{
				return this._ParentCode;
			}
			set
			{
				if ((this._ParentCode != value))
				{
					this.OnParentCodeChanging(value);
					this.SendPropertyChanging();
					this._ParentCode = value;
					this.SendPropertyChanged("ParentCode");
					this.OnParentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettingCat", DbType="NVarChar(25)")]
		public string SettingCat
		{
			get
			{
				return this._SettingCat;
			}
			set
			{
				if ((this._SettingCat != value))
				{
					this.OnSettingCatChanging(value);
					this.SendPropertyChanging();
					this._SettingCat = value;
					this.SendPropertyChanged("SettingCat");
					this.OnSettingCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WHCode", DbType="NVarChar(50)")]
		public string WHCode
		{
			get
			{
				return this._WHCode;
			}
			set
			{
				if ((this._WHCode != value))
				{
					this.OnWHCodeChanging(value);
					this.SendPropertyChanging();
					this._WHCode = value;
					this.SendPropertyChanged("WHCode");
					this.OnWHCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameVI", DbType="NVarChar(255)")]
		public string NameVI
		{
			get
			{
				return this._NameVI;
			}
			set
			{
				if ((this._NameVI != value))
				{
					this.OnNameVIChanging(value);
					this.SendPropertyChanging();
					this._NameVI = value;
					this.SendPropertyChanged("NameVI");
					this.OnNameVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameEN", DbType="NVarChar(255)")]
		public string NameEN
		{
			get
			{
				return this._NameEN;
			}
			set
			{
				if ((this._NameEN != value))
				{
					this.OnNameENChanging(value);
					this.SendPropertyChanging();
					this._NameEN = value;
					this.SendPropertyChanged("NameEN");
					this.OnNameENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameFormatVI", DbType="NVarChar(255)")]
		public string NameFormatVI
		{
			get
			{
				return this._NameFormatVI;
			}
			set
			{
				if ((this._NameFormatVI != value))
				{
					this.OnNameFormatVIChanging(value);
					this.SendPropertyChanging();
					this._NameFormatVI = value;
					this.SendPropertyChanged("NameFormatVI");
					this.OnNameFormatVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameFormatEN", DbType="NVarChar(255)")]
		public string NameFormatEN
		{
			get
			{
				return this._NameFormatEN;
			}
			set
			{
				if ((this._NameFormatEN != value))
				{
					this.OnNameFormatENChanging(value);
					this.SendPropertyChanging();
					this._NameFormatEN = value;
					this.SendPropertyChanged("NameFormatEN");
					this.OnNameFormatENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JsonStr", DbType="NVarChar(MAX)")]
		public string JsonStr
		{
			get
			{
				return this._JsonStr;
			}
			set
			{
				if ((this._JsonStr != value))
				{
					this.OnJsonStrChanging(value);
					this.SendPropertyChanging();
					this._JsonStr = value;
					this.SendPropertyChanged("JsonStr");
					this.OnJsonStrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lsttbl_Widget")]
	public partial class lsttbl_Widget : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private string _Code;
		
		private string _Name;
		
		private string _WidgetType;
		
		private string _DSCode;
		
		private string _WHCode;
		
		private string _JsonStr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnWidgetTypeChanging(string value);
    partial void OnWidgetTypeChanged();
    partial void OnDSCodeChanging(string value);
    partial void OnDSCodeChanged();
    partial void OnWHCodeChanging(string value);
    partial void OnWHCodeChanged();
    partial void OnJsonStrChanging(string value);
    partial void OnJsonStrChanged();
    #endregion
		
		public lsttbl_Widget()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WidgetType", DbType="NVarChar(50)")]
		public string WidgetType
		{
			get
			{
				return this._WidgetType;
			}
			set
			{
				if ((this._WidgetType != value))
				{
					this.OnWidgetTypeChanging(value);
					this.SendPropertyChanging();
					this._WidgetType = value;
					this.SendPropertyChanged("WidgetType");
					this.OnWidgetTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSCode", DbType="NVarChar(50)")]
		public string DSCode
		{
			get
			{
				return this._DSCode;
			}
			set
			{
				if ((this._DSCode != value))
				{
					this.OnDSCodeChanging(value);
					this.SendPropertyChanging();
					this._DSCode = value;
					this.SendPropertyChanged("DSCode");
					this.OnDSCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WHCode", DbType="NVarChar(50)")]
		public string WHCode
		{
			get
			{
				return this._WHCode;
			}
			set
			{
				if ((this._WHCode != value))
				{
					this.OnWHCodeChanging(value);
					this.SendPropertyChanging();
					this._WHCode = value;
					this.SendPropertyChanged("WHCode");
					this.OnWHCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JsonStr", DbType="NVarChar(MAX)")]
		public string JsonStr
		{
			get
			{
				return this._JsonStr;
			}
			set
			{
				if ((this._JsonStr != value))
				{
					this.OnJsonStrChanging(value);
					this.SendPropertyChanging();
					this._JsonStr = value;
					this.SendPropertyChanged("JsonStr");
					this.OnJsonStrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lsttbl_WidgetInteraction")]
	public partial class lsttbl_WidgetInteraction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private string _WidgetCode;
		
		private string _JsonStr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnWidgetCodeChanging(string value);
    partial void OnWidgetCodeChanged();
    partial void OnJsonStrChanging(string value);
    partial void OnJsonStrChanged();
    #endregion
		
		public lsttbl_WidgetInteraction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WidgetCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WidgetCode
		{
			get
			{
				return this._WidgetCode;
			}
			set
			{
				if ((this._WidgetCode != value))
				{
					this.OnWidgetCodeChanging(value);
					this.SendPropertyChanging();
					this._WidgetCode = value;
					this.SendPropertyChanged("WidgetCode");
					this.OnWidgetCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JsonStr", DbType="NVarChar(MAX)")]
		public string JsonStr
		{
			get
			{
				return this._JsonStr;
			}
			set
			{
				if ((this._JsonStr != value))
				{
					this.OnJsonStrChanging(value);
					this.SendPropertyChanging();
					this._JsonStr = value;
					this.SendPropertyChanged("JsonStr");
					this.OnJsonStrChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lsttbl_DWColumn")]
	public partial class lsttbl_DWColumn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private bool _Visible;
		
		private string _TblName_Actual;
		
		private string _TblName_Virtual;
		
		private string _ColName;
		
		private string _ColAliasVI;
		
		private string _ColAliasEN;
		
		private string _DataType;
		
		private bool _IsKey;
		
		private EntityRef<lsttbl_DWTable> _lsttbl_DWTable;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnVisibleChanging(bool value);
    partial void OnVisibleChanged();
    partial void OnTblName_ActualChanging(string value);
    partial void OnTblName_ActualChanged();
    partial void OnTblName_VirtualChanging(string value);
    partial void OnTblName_VirtualChanged();
    partial void OnColNameChanging(string value);
    partial void OnColNameChanged();
    partial void OnColAliasVIChanging(string value);
    partial void OnColAliasVIChanged();
    partial void OnColAliasENChanging(string value);
    partial void OnColAliasENChanged();
    partial void OnDataTypeChanging(string value);
    partial void OnDataTypeChanged();
    partial void OnIsKeyChanging(bool value);
    partial void OnIsKeyChanged();
    #endregion
		
		public lsttbl_DWColumn()
		{
			this._lsttbl_DWTable = default(EntityRef<lsttbl_DWTable>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visible", DbType="Bit NOT NULL")]
		public bool Visible
		{
			get
			{
				return this._Visible;
			}
			set
			{
				if ((this._Visible != value))
				{
					this.OnVisibleChanging(value);
					this.SendPropertyChanging();
					this._Visible = value;
					this.SendPropertyChanged("Visible");
					this.OnVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TblName_Actual", DbType="NVarChar(100)")]
		public string TblName_Actual
		{
			get
			{
				return this._TblName_Actual;
			}
			set
			{
				if ((this._TblName_Actual != value))
				{
					this.OnTblName_ActualChanging(value);
					this.SendPropertyChanging();
					this._TblName_Actual = value;
					this.SendPropertyChanged("TblName_Actual");
					this.OnTblName_ActualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TblName_Virtual", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TblName_Virtual
		{
			get
			{
				return this._TblName_Virtual;
			}
			set
			{
				if ((this._TblName_Virtual != value))
				{
					if (this._lsttbl_DWTable.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTblName_VirtualChanging(value);
					this.SendPropertyChanging();
					this._TblName_Virtual = value;
					this.SendPropertyChanged("TblName_Virtual");
					this.OnTblName_VirtualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ColName
		{
			get
			{
				return this._ColName;
			}
			set
			{
				if ((this._ColName != value))
				{
					this.OnColNameChanging(value);
					this.SendPropertyChanging();
					this._ColName = value;
					this.SendPropertyChanged("ColName");
					this.OnColNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColAliasVI", DbType="NVarChar(100)")]
		public string ColAliasVI
		{
			get
			{
				return this._ColAliasVI;
			}
			set
			{
				if ((this._ColAliasVI != value))
				{
					this.OnColAliasVIChanging(value);
					this.SendPropertyChanging();
					this._ColAliasVI = value;
					this.SendPropertyChanged("ColAliasVI");
					this.OnColAliasVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColAliasEN", DbType="NVarChar(100)")]
		public string ColAliasEN
		{
			get
			{
				return this._ColAliasEN;
			}
			set
			{
				if ((this._ColAliasEN != value))
				{
					this.OnColAliasENChanging(value);
					this.SendPropertyChanging();
					this._ColAliasEN = value;
					this.SendPropertyChanged("ColAliasEN");
					this.OnColAliasENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DataType
		{
			get
			{
				return this._DataType;
			}
			set
			{
				if ((this._DataType != value))
				{
					this.OnDataTypeChanging(value);
					this.SendPropertyChanging();
					this._DataType = value;
					this.SendPropertyChanged("DataType");
					this.OnDataTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsKey", DbType="Bit NOT NULL")]
		public bool IsKey
		{
			get
			{
				return this._IsKey;
			}
			set
			{
				if ((this._IsKey != value))
				{
					this.OnIsKeyChanging(value);
					this.SendPropertyChanging();
					this._IsKey = value;
					this.SendPropertyChanged("IsKey");
					this.OnIsKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lsttbl_DWTable_lsttbl_DWColumn", Storage="_lsttbl_DWTable", ThisKey="TblName_Virtual", OtherKey="TblName", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public lsttbl_DWTable lsttbl_DWTable
		{
			get
			{
				return this._lsttbl_DWTable.Entity;
			}
			set
			{
				lsttbl_DWTable previousValue = this._lsttbl_DWTable.Entity;
				if (((previousValue != value) 
							|| (this._lsttbl_DWTable.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lsttbl_DWTable.Entity = null;
						previousValue.lsttbl_DWColumns.Remove(this);
					}
					this._lsttbl_DWTable.Entity = value;
					if ((value != null))
					{
						value.lsttbl_DWColumns.Add(this);
						this._TblName_Virtual = value.TblName;
					}
					else
					{
						this._TblName_Virtual = default(string);
					}
					this.SendPropertyChanged("lsttbl_DWTable");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lsttbl_DWTableRelationship")]
	public partial class lsttbl_DWTableRelationship : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private string _WHCode;
		
		private string _Parent;
		
		private string _Children;
		
		private string _LinkedField;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnWHCodeChanging(string value);
    partial void OnWHCodeChanged();
    partial void OnParentChanging(string value);
    partial void OnParentChanged();
    partial void OnChildrenChanging(string value);
    partial void OnChildrenChanged();
    partial void OnLinkedFieldChanging(string value);
    partial void OnLinkedFieldChanged();
    #endregion
		
		public lsttbl_DWTableRelationship()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WHCode", DbType="NVarChar(50)")]
		public string WHCode
		{
			get
			{
				return this._WHCode;
			}
			set
			{
				if ((this._WHCode != value))
				{
					this.OnWHCodeChanging(value);
					this.SendPropertyChanging();
					this._WHCode = value;
					this.SendPropertyChanged("WHCode");
					this.OnWHCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this.OnParentChanging(value);
					this.SendPropertyChanging();
					this._Parent = value;
					this.SendPropertyChanged("Parent");
					this.OnParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Children", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Children
		{
			get
			{
				return this._Children;
			}
			set
			{
				if ((this._Children != value))
				{
					this.OnChildrenChanging(value);
					this.SendPropertyChanging();
					this._Children = value;
					this.SendPropertyChanged("Children");
					this.OnChildrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkedField", DbType="NVarChar(400) NOT NULL", CanBeNull=false)]
		public string LinkedField
		{
			get
			{
				return this._LinkedField;
			}
			set
			{
				if ((this._LinkedField != value))
				{
					this.OnLinkedFieldChanging(value);
					this.SendPropertyChanging();
					this._LinkedField = value;
					this.SendPropertyChanged("LinkedField");
					this.OnLinkedFieldChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.systbl_Menu")]
	public partial class systbl_Menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private bool _IsDefault;
		
		private bool _Visible;
		
		private string _SortOrder;
		
		private string _ParentCode;
		
		private string _Code;
		
		private string _Url;
		
		private string _NameVI;
		
		private string _NameEN;
		
		private string _Image;
		
		private EntitySet<systbl_UserMenu> _systbl_UserMenus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnIsDefaultChanging(bool value);
    partial void OnIsDefaultChanged();
    partial void OnVisibleChanging(bool value);
    partial void OnVisibleChanged();
    partial void OnSortOrderChanging(string value);
    partial void OnSortOrderChanged();
    partial void OnParentCodeChanging(string value);
    partial void OnParentCodeChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnNameVIChanging(string value);
    partial void OnNameVIChanged();
    partial void OnNameENChanging(string value);
    partial void OnNameENChanged();
    partial void OnImageChanging(string value);
    partial void OnImageChanged();
    #endregion
		
		public systbl_Menu()
		{
			this._systbl_UserMenus = new EntitySet<systbl_UserMenu>(new Action<systbl_UserMenu>(this.attach_systbl_UserMenus), new Action<systbl_UserMenu>(this.detach_systbl_UserMenus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDefault", DbType="Bit NOT NULL")]
		public bool IsDefault
		{
			get
			{
				return this._IsDefault;
			}
			set
			{
				if ((this._IsDefault != value))
				{
					this.OnIsDefaultChanging(value);
					this.SendPropertyChanging();
					this._IsDefault = value;
					this.SendPropertyChanged("IsDefault");
					this.OnIsDefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visible", DbType="Bit NOT NULL")]
		public bool Visible
		{
			get
			{
				return this._Visible;
			}
			set
			{
				if ((this._Visible != value))
				{
					this.OnVisibleChanging(value);
					this.SendPropertyChanging();
					this._Visible = value;
					this.SendPropertyChanged("Visible");
					this.OnVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this.OnSortOrderChanging(value);
					this.SendPropertyChanging();
					this._SortOrder = value;
					this.SendPropertyChanged("SortOrder");
					this.OnSortOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCode", DbType="NVarChar(50)")]
		public string ParentCode
		{
			get
			{
				return this._ParentCode;
			}
			set
			{
				if ((this._ParentCode != value))
				{
					this.OnParentCodeChanging(value);
					this.SendPropertyChanging();
					this._ParentCode = value;
					this.SendPropertyChanged("ParentCode");
					this.OnParentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(50)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameVI", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NameVI
		{
			get
			{
				return this._NameVI;
			}
			set
			{
				if ((this._NameVI != value))
				{
					this.OnNameVIChanging(value);
					this.SendPropertyChanging();
					this._NameVI = value;
					this.SendPropertyChanged("NameVI");
					this.OnNameVIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameEN", DbType="NVarChar(255)")]
		public string NameEN
		{
			get
			{
				return this._NameEN;
			}
			set
			{
				if ((this._NameEN != value))
				{
					this.OnNameENChanging(value);
					this.SendPropertyChanging();
					this._NameEN = value;
					this.SendPropertyChanged("NameEN");
					this.OnNameENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="NVarChar(255)")]
		public string Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="systbl_Menu_systbl_UserMenu", Storage="_systbl_UserMenus", ThisKey="Code", OtherKey="MenuCode")]
		public EntitySet<systbl_UserMenu> systbl_UserMenus
		{
			get
			{
				return this._systbl_UserMenus;
			}
			set
			{
				this._systbl_UserMenus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_systbl_UserMenus(systbl_UserMenu entity)
		{
			this.SendPropertyChanging();
			entity.systbl_Menu = this;
		}
		
		private void detach_systbl_UserMenus(systbl_UserMenu entity)
		{
			this.SendPropertyChanging();
			entity.systbl_Menu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lsttbl_Dashboard")]
	public partial class lsttbl_Dashboard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private bool _IsDefault;
		
		private string _WHCode;
		
		private string _Code;
		
		private string _Name;
		
		private string _JsonStr;
		
		private EntitySet<systbl_UserDashboard> _systbl_UserDashboards;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnIsDefaultChanging(bool value);
    partial void OnIsDefaultChanged();
    partial void OnWHCodeChanging(string value);
    partial void OnWHCodeChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnJsonStrChanging(string value);
    partial void OnJsonStrChanged();
    #endregion
		
		public lsttbl_Dashboard()
		{
			this._systbl_UserDashboards = new EntitySet<systbl_UserDashboard>(new Action<systbl_UserDashboard>(this.attach_systbl_UserDashboards), new Action<systbl_UserDashboard>(this.detach_systbl_UserDashboards));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDefault", DbType="Bit NOT NULL")]
		public bool IsDefault
		{
			get
			{
				return this._IsDefault;
			}
			set
			{
				if ((this._IsDefault != value))
				{
					this.OnIsDefaultChanging(value);
					this.SendPropertyChanging();
					this._IsDefault = value;
					this.SendPropertyChanged("IsDefault");
					this.OnIsDefaultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WHCode", DbType="NVarChar(50)")]
		public string WHCode
		{
			get
			{
				return this._WHCode;
			}
			set
			{
				if ((this._WHCode != value))
				{
					this.OnWHCodeChanging(value);
					this.SendPropertyChanging();
					this._WHCode = value;
					this.SendPropertyChanged("WHCode");
					this.OnWHCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JsonStr", DbType="NVarChar(MAX)")]
		public string JsonStr
		{
			get
			{
				return this._JsonStr;
			}
			set
			{
				if ((this._JsonStr != value))
				{
					this.OnJsonStrChanging(value);
					this.SendPropertyChanging();
					this._JsonStr = value;
					this.SendPropertyChanged("JsonStr");
					this.OnJsonStrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="lsttbl_Dashboard_systbl_UserDashboard", Storage="_systbl_UserDashboards", ThisKey="Code", OtherKey="DbrdCode")]
		public EntitySet<systbl_UserDashboard> systbl_UserDashboards
		{
			get
			{
				return this._systbl_UserDashboards;
			}
			set
			{
				this._systbl_UserDashboards.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_systbl_UserDashboards(systbl_UserDashboard entity)
		{
			this.SendPropertyChanging();
			entity.lsttbl_Dashboard = this;
		}
		
		private void detach_systbl_UserDashboards(systbl_UserDashboard entity)
		{
			this.SendPropertyChanging();
			entity.lsttbl_Dashboard = null;
		}
	}
}
#pragma warning restore 1591
